### ISSUE TITLE
[Feature Request/Bug?] Config Compatibility with "Make Bubbles Pop" Mod

### ISSUE THREAD

**Issue by meowinqq** [wVibzz/ImmersiveWinds#13]
The particle bubbles introduced by "Make Bubbles Pop" don't seem to have a blacklist toggle in the config and are effected by wind. Blacklisting the vanilla "bubble," "bubble pop," and "bubble column up" particles has no effect. I've labeled this as either a feature request or a bug because I've no clue as to whether or not a bug is causing the mod to not be detected. :')
Thank you so much for all of the time and energy you've put into this project, this seriously is one of the best mods out there!

**Comment by wVibzz** [comment]
I'll look into it and see what I can do

**Comment by wVibzz** [comment]
Ok I have found the solution, there was an overlook in my code that still affected particles that where in a fluid. that has been fixed, 
also the reason it doesn't create a separate class for the mod is because they aren't adding any particles just changing Minecraft's default ones. so they will be listed under Minecraft

this change will be implemented in the next update
