### ISSUE TITLE
Feature Request: Toggle winds for dimensions

### ISSUE THREAD

**Issue by Roadhog360** [wVibzz/ImmersiveWinds#14]
Wind applies to particles in the Nether and End
Proposed solution:
Ability to blacklist certain dimensions, and option to use the blacklist as a whitelist instead. Default blacklist would be minecraft:nether and minecraft:the_end

**Comment by wVibzz** [comment]
This is a good idea, Ill work on adding this, I could add a 'Toggle All' button for your supposed whitelist if that would fit your needs.

**Comment by wVibzz** [comment]
Also the wind being in the End and Nether are on purpose. I did think about this before adding it, logically you would need wind (or air) in the End for the dragon to fly. And also in the Nether for particles to float, (like the grey ash particle) it would need air.

Also any empty block is an air block.

**Comment by Roadhog360** [comment]
I would say that it's pretty heavily implied that there is no wind in the Nether; it's essentially a huge cave. There's plenty of reasons why the particles might be moving on their own, such as the warped/crimson forest shooting spores, deltas having lava create small updrafts, and... actually the soul sand valley does have a wind sound effect, so maybe that could have wind? It's hard to say. Maybe an option for wind multipliers for each dimension? I'd personally set the Nether to a low multiplier, likely 0.2. The soul sand valley could have more wind due to its windy sounds. I don't think there's any reason for wind to be in the end, I'd expect it to have still air.

**Comment by wVibzz** [comment]
I looked into it and think your approach seems correct

There is nothing in the end that proves that there is wind, since all you need is air to fly.
And the fact there is nothing there that would produce wind either.

But in the Nether having a little wind makes sense.  But its generated by the Immense amount of heat.
Since heat rises and cools off that actually produces wind from Convection and Updrafts, this can also be 
proved by the fact that smoke also rises from fire in the nether which means there's a presence of cold and hot air
although it is 'theoretical'. 
But I do agree that there should be less wind in the Nether and no wind in the End.
Ill make some changes.

**Comment by Roadhog360** [comment]
Yes, thank you. So we know that the basalt deltas probably have some minor updrafts, and the soul Sand valley has wind of an unknown source due to its audio design. So I would suggest if you don't want to do biome specific wind values, that you just make it the same small level all throughout the nether. 

But I can't see there being any specific wind direction, I would theoretically believe that the nether would have sporadic wind pattern changes, because the fire is everywhere so I would assume that they're updrafts that would change the wind direction frequently. So I suggest that the direction of the wind changes more frequently than in the overworld, but the push of wind is less noticeable overall.

**Comment by wVibzz** [comment]
I like that. Ill see what I can do

**Comment by wVibzz** [comment]
I have made it so that there is only wind in the overworld. and have layed a basis for updraft physics. This will be included in the next update
