### ISSUE TITLE
Compatibility with season mods

### ISSUE THREAD

**Issue by JorisDeBeer** [wVibzz/ImmersiveWinds#15]
Hi, firstly wanna say what ur doing here is great work. Always wanted a localized weather/wind system in minecraft to make it more realistic. 

There should be a fix in place for season mods tho, as they alter the particles as wel in some settings (rain changing to snow in the same biome). Your custom rain particles cause it to not actually snow but it shows the rain particles in winter while snow gets accumulated on the ground. 

Bit of a bummer but when you get time/want to hopefully you can fix this! 

I am looking forward to more updates! :)

**Comment by wVibzz** [comment]
This is interesting but there isn't actually much I can do about it. I currently use Particle Rain as a dependency for my mod that creates the particle snow and rain. So until I finish making my own particles so that my mod is standalone I cant do anything about this.

If you install mod menu and go into the Particle Rain Config You can enable the vanilla rendering of the regular weather and disable the particle rain/snow, it should work while still doing the other wind stuff from my mod. You just wont have wind affecting snow/rain.
