### ISSUE TITLE
Request: Feature separation or a lite version

### ISSUE THREAD

**Issue by RMEngelbrecht** [wVibzz/ImmersiveWinds#28]
I really like the mod and it's premise, however the roadmap scares me a bit.
Not saying they're not good ideas, but I'm scared cramming them all into a single mod would make it less suitable for packs.

For instance: the new cloud system sounds good, however many people right now enjoy the Better Clouds mod as a substitute for clouds (off topic but: integration? 👀). Having to choose between wind at all and my favourite cloud mod isn't something I'm looking forward to.

Same goes for underwater currents, personally would like to see that in a separate mod rather than integrated into a winds mod. Would absolutely install both in my personal game, but would like to have the option to choose when it comes to assembling packs.

Other than that I absolutely love this mod already and I'm looking forward to what it's future brings. Keep up the good work!

**Comment by wVibzz** [comment]
I have thought of this and am glad you mentioned it. I've looked at this mod before and wanted to make my own cloud system for various reasons.

Better Clouds uses the minecraft cloud system and adds various features to it. What I plan is to add volumetric clouds more like [this mod](https://modrinth.com/mod/betterweather/gallery)
and then add localized weather to it also like said mod. 
Also so that I can integrate my clouds to work with my wind engine way better with refined control and also adding various weathers.

However I do believe you are right about separating mods. And will probably be doing so.

**Comment by Golblahaj** [comment]
The underwater currents thing would be absolutely incredible though, always wanted to see something similar. Perhaps a config for turning things off and on when generating a world?
