### ISSUE TITLE
Particle velocity behaves weirdly and snaps sometimes

### ISSUE THREAD

**Issue by BakinDP** [wVibzz/ImmersiveWinds#3]
Version 0.4 of Immersive Winds.

1) The mod doesn't respect current weather. Particles are still affected in clear weather, expected to have zero or little velocity.
2) With uncertain conditions and actions (once it happened after accessing Particle Rain options, but never again) the velocity of particles becomes crazy big and remains like it for the entire game session or config reload ( https://youtu.be/-a1pTVzVmjU ).

**Comment by wVibzz** [comment]
There is three weather states. Clear, Rain, and Thunder. 

```
private static int calculateNewWindStrength(World world) {
        // Wind strength is calculated to follow this scale: "https://www.weather.gov/pqr/wind" up to 45mph or 8/Gale
        // It's not really a perfect 1:1
        if (world.isThundering()) {
            return random.nextInt(13) + 32; // 32 -> 44
        } else if (world.isRaining()) {
            return random.nextInt(20) + 12; // 12 -> 31
        } else {
            return random.nextInt(10) + 1;  // 1 -> 11
        }
    }
```


when the weather is clear. there will still be wind but very weak.


also when changing weather, clear -> rain, there will be a delay from the clear strength to the rain strength to simulate wind picking up.

If others feel the same about the strength I could lessen it for less drift when its clear. Or have less updates when clear.


2. The reason the particles velocity went big is because the wind transitioned from clear -> rain/thunder while you changed settings.
